# Generated by Django 4.2.20 on 2025-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTaro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_meaning', models.TextField()),
                ('description_advance', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
